# Generated by Django 5.0.2 on 2024-03-25 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room_nums',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='room_nums',
            name='to_date',
        ),
    ]
