# Generated by Django 5.0.2 on 2024-03-25 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_remove_room_nums_from_date_remove_room_nums_to_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('room_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.room_nums')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.staffs')),
            ],
        ),
    ]
