# Generated by Django 5.0.2 on 2024-03-25 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_room_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room_book',
            name='room_num',
        ),
        migrations.RemoveField(
            model_name='room_book',
            name='user',
        ),
    ]
