# Generated by Django 5.0.2 on 2024-03-26 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_room_book_hostel_name_room_book_room_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_book',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hostel.staffs'),
            preserve_default=False,
        ),
    ]
