# Generated by Django 5.0.2 on 2024-03-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_rename_user_room_book_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_book',
            name='status',
            field=models.IntegerField(),
        ),
    ]
