# Generated by Django 5.0.2 on 2024-04-01 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0008_alter_room_book_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room_nums',
            name='status',
        ),
    ]
